# docker-compose.yaml
version: '3'

services:
        review_cycle:
                restart: unless-stopped
                build:
                        context: .
                        dockerfile: docker/Dockerfile
                container_name: review_cycle
                tty: true
                networks:
                    - review_cycle-network
                depends_on:
                        - db_dev
                environment:
                        DATABASE_URL: postgresql://dbuser:password@127.0.0.1:5432/review_cycle_dev
                        ENV: dev
                working_dir: /var/www
                volumes:
                        - ./:/var/www

        review_cycle_webserver:
                image: nginx:stable
                container_name: review_cycle_webserver
                restart: unless-stopped
                networks:
                    - review_cycle-network
                ports:
                        - "80:80"
                depends_on:
                        - review_cycle
                volumes:
                        - ./:/var/www
                        - ./docker/app.conf:/etc/nginx/conf.d/default.conf
                links:
                        - review_cycle

        db_dev:
                image: postgres:13
                container_name: db_dev
                restart: unless-stopped
                networks:
                    - review_cycle-network
                volumes:
                        - db_data:/var/lib/postgresql/data
                environment:
                        POSTGRES_PASSWORD: password
                        POSTGRES_USER: dbuser
                        POSTGRES_DB: review_cycle_dev
                ports:
                        - "54320:5432"

        db_test:
                image: postgres:13
                container_name: db_test
                restart: unless-stopped
                networks:
                    - review_cycle-network
                volumes:
                        - db_data_test:/var/lib/postgresql/data
                environment:
                        POSTGRES_PASSWORD: testsecret
                        POSTGRES_USER: testuser
                        POSTGRES_DB: review_cycle_test
                ports:
                        - "54321:5432"

volumes:
        db_data:
        db_data_test:

networks:
    review_cycle-network:
        driver: bridge
